In [115]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path
import os

pd.set_option('display.max_columns', None)

In [24]:
base_path = Path().resolve().parent
file_path = base_path / "current_raw_data" / "combined_data.csv"

df = pd.read_csv(file_path)

In [25]:
df.head()

,Restaurant Type,Restaurant Category,Cuisine Type,Restaurant Name,Restaurant Description,Top Selling Cuisine,Time of Order,Order Delivered Date,Time of Delivery,Expected Delivery Time,...,Total Number of Reviews,Number of Complaints Received,Foot Traffic in Location,Competitors in the Area (Count),Budgetd_Rev,Budgetd_Operating Cost,Budgeted Order,Budgeted GP,Acquisition cost,Value
0,Casual Dining,Snack,Continental,SodaBottleOpenerWala,"[*Parsi, North Indian, Street Food, Desserts, ...",Pizza,0.618750,2021-03-01,0.580556,40,...,441,5,medium,18,417.560000,264.320000,252.0,133.620000,13.280000,509.3800
1,Delivery,Snack,Vegetarian Snacks,SodaBottleOpenerWala,"[*Parsi, North Indian, Street Food, Desserts, ...",Bhel Puri,0.604016,2021-03-01,0.629711,48,...,319,33,High,10,385.968888,299.566028,0.0,86.402860,13.392857,84.4308
2,Casual Dining,Snack,Continental,Pizza By The Bay,"[*Italian, Fast Food, Beverages~]\",Pizza,0.441667,2021-03-01,0.204861,45,...,371,1,low,6,825.280000,477.040000,229.0,289.540000,11.860000,957.3700
3,Delivery,Snack,Vegetarian Snacks,SodaBottleOpenerWala,"[*Parsi, North Indian, Street Food, Desserts, ...",Bhel Puri,0.604016,2021-03-01,0.629711,48,...,319,33,High,10,389.354580,266.826387,0.0,122.528194,17.117117,84.4308
4,Casual Dining,Snack,Continental,Global Fusion,"[*Chinese, Desserts, Beverages~]\",Pizza,0.473611,2021-03-01,0.509722,45,...,285,4,high,10,472.580000,279.270000,281.0,155.940000,17.570000,574.1900

In [26]:
df.shape

(2120, 44)

# **Data Cleaning**

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2120 entries, 0 to 2119
Data columns (total 44 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Restaurant Type                  2120 non-null   object
 1   Restaurant Category              2120 non-null   object
 2   Cuisine Type                     2120 non-null   object
 3   Restaurant Name                  2120 non-null   object
 4   Restaurant Description           2120 non-null   object
 5   Top Selling Cuisine              2120 non-null   object
 6   Time of Order                    2120 non-null   float64
 7   Order Delivered Date             2120 non-null   object
 8   Time of Delivery                 2120 non-null   float64
 9   Expected Delivery Time           2120 non-null   int64
 10  Delivery Time (in mins)          2120 non-null   int64
 11  Restaurant_ID                    2120 non-null   int64
 12  Desc_ID                          2120 non-null   int64
 13  Restaurant Location              2120 non-null   object
 14  Average Rating                   2120 non-null   float64
 15  Restaurant Type.1                2120 non-null   object
 16  Category_ID                      2120 non-null   int64
 17  Cuisine_ID                       2120 non-null   int64
 18  Working Hrs                      2120 non-null   object
 19  Delivery Available               2120 non-null   object
 20  Table Booking Available          2120 non-null   object
 21  Closed On?                       724 non-null    object
 22  Price                            2120 non-null   int64
 23  Discounts Offered (%)            2120 non-null   float64
 24  Discounted Price                 2120 non-null   float64
 25  Expected Revenue                 2120 non-null   float64
 26  Customer Name                    2120 non-null   object
 27  Average Rating.1                 2120 non-null   float64
 28  Order Status?                    2120 non-null   object
 29  Cancellation Reason              2120 non-null   object
 30  Subscription                     2120 non-null   object
 31  Actual Revenue                   2120 non-null   float64
 32  Operating Cost                   2120 non-null   float64
 33  GP Margin                        2120 non-null   float64
 34  Total Number of Reviews          2120 non-null   int64
 35  Number of Complaints Received    2120 non-null   int64
 36  Foot Traffic in Location         2120 non-null   object
 37  Competitors in the Area (Count)  2120 non-null   int64
 38  Budgetd_Rev                      2120 non-null   float64
 39  Budgetd_Operating Cost           2120 non-null   float64
 40  Budgeted Order                   2120 non-null   float64
 41  Budgeted GP                      2120 non-null   float64
 42  Acquisition cost                 2120 non-null   float64
 43  Value                            2120 non-null   float64
dtypes: float64(16), int64(10), object(18)
memory usage: 728.9+ KB

In [28]:
df.describe()

,Time of Order,Time of Delivery,Expected Delivery Time,Delivery Time (in mins),Restaurant_ID,Desc_ID,Average Rating,Category_ID,Cuisine_ID,Price,...,GP Margin,Total Number of Reviews,Number of Complaints Received,Competitors in the Area (Count),Budgetd_Rev,Budgetd_Operating Cost,Budgeted Order,Budgeted GP,Acquisition cost,Value
count,2120.000000,2120.000000,2120.000000,2120.000000,2120.000000,2120.000000,2120.000000,2120.000000,2120.000000,2120.000000,...,2120.000000,2120.000000,2120.000000,2120.000000,2120.000000,2120.000000,2120.000000,2120.000000,2120.000000,2120.000000
mean,0.514542,0.531312,48.439623,43.376415,17.599057,180.982075,4.409481,3.535849,6.702358,682.650472,...,49.463702,232.781132,42.058962,21.492925,490.994511,430.483898,50.035849,56.289905,16.383720,200.133017
std,0.290456,0.293067,9.119165,7.315115,21.172400,363.862968,0.221518,2.309191,4.312104,375.138462,...,213.731319,119.922734,31.760635,13.335364,418.452268,262.732718,107.780328,241.152258,3.358077,247.743946
min,0.001389,0.000000,30.000000,20.000000,1.000000,1.000000,4.000000,1.000000,1.000000,80.000000,...,-593.684100,31.000000,0.000000,1.000000,0.000000,49.465416,0.000000,-676.799874,10.050000,3.686000
25%,0.253831,0.270301,42.000000,39.000000,5.000000,5.000000,4.200000,1.000000,4.000000,380.000000,...,-56.945700,133.000000,13.000000,9.000000,0.000000,214.419235,0.000000,-64.491005,14.285714,40.948400
50%,0.532292,0.532998,49.000000,42.000000,12.000000,12.000000,4.400000,3.000000,5.000000,613.000000,...,111.355680,224.000000,36.000000,20.500000,486.770000,413.794920,0.000000,126.161552,15.789474,92.018000
75%,0.782940,0.810289,57.000000,49.000000,18.000000,20.000000,4.600000,5.000000,10.000000,971.000000,...,194.915280,326.000000,68.000000,32.000000,765.342500,574.243169,0.000000,217.339374,17.391304,295.838400
max,0.999306,0.995139,65.000000,60.000000,99.000000,999.000000,4.700000,10.000000,20.000000,1480.000000,...,412.290000,500.000000,99.000000,50.000000,1427.312840,1131.921139,350.000000,513.520000,29.910000,1292.110000

In [29]:
df.isnull().sum()

Restaurant Type                       0
Restaurant Category                   0
Cuisine Type                          0
Restaurant Name                       0
Restaurant Description                0
Top Selling Cuisine                   0
Time of Order                         0
Order Delivered Date                  0
Time of Delivery                      0
Expected Delivery Time                0
Delivery Time (in mins)               0
Restaurant_ID                         0
Desc_ID                               0
Restaurant Location                   0
Average Rating                        0
Restaurant Type.1                     0
Category_ID                           0
Cuisine_ID                            0
Working Hrs                           0
Delivery Available                    0
Table Booking Available               0
Closed On?                         1396
Price                                 0
Discounts Offered (%)                 0
Discounted Price                      0
Expected Revenue                      0
Customer Name                         0
Average Rating.1                      0
Order Status?                         0
Cancellation Reason                   0
Subscription                          0
Actual Revenue                        0
Operating Cost                        0
GP Margin                             0
Total Number of Reviews               0
Number of Complaints Received         0
Foot Traffic in Location              0
Competitors in the Area (Count)       0
Budgetd_Rev                           0
Budgetd_Operating Cost                0
Budgeted Order                        0
Budgeted GP                           0
Acquisition cost                      0
Value                                 0
dtype: int64

In [45]:
df.drop(columns=['Closed On?'],inplace=True)

In [46]:
df.shape

(2120, 43)

In [52]:
new_columns = []

for col in df.columns:
    col = col.strip()        # remove leading & trailing spaces
    col = col.lower()        # convert to lowercase
    col = col.replace(' ', '_')  # replace spaces with underscore
    new_columns.append(col)

df.columns = new_columns

In [135]:
df.columns

Index(['restaurant_type', 'restaurant_category', 'cuisine_type',
       'restaurant_name', 'restaurant_description', 'top_selling_cuisine',
       'time_of_order', 'order_delivered_date', 'time_of_delivery',
       'expected_delivery_time', 'delivery_time_in_mins', 'restaurant_id',
       'desc_id', 'restaurant_location', 'average_rating', 'category_id',
       'cuisine_id', 'working_hrs', 'delivery_available',
       'table_booking_available', 'price', 'discounts_offered_pct',
       'discounted_price', 'expected_revenue', 'average_rating_1',
       'order_status', 'cancellation_reason', 'subscription', 'actual_revenue',
       'operating_cost', 'gp_margin', 'total_number_of_reviews',
       'number_of_complaints_received', 'foot_traffic_in_location',
       'competitors_in_the_area_count', 'budgetd_rev',
       'budgetd_operating_cost', 'budgeted_order', 'budgeted_gp',
       'acquisition_cost', 'value'],
      dtype='object')

In [134]:
df.rename(columns={
    'delivery_time_(in_mins)': 'delivery_time_in_mins',
    'discounts_offered_(%)': 'discounts_offered_pct',
    'average_rating.1': 'average_rating_1',
    'competitors_in_the_area_(count)': 'competitors_in_the_area_count'
}, inplace=True)

In [56]:
df.rename(columns={'order_status?':'order_status'},inplace=True)

In [119]:
df.duplicated().sum()

np.int64(207)

In [120]:
df = df.drop_duplicates()

In [58]:
df[['restaurant_type','restaurant_type.1']]

     restaurant_type restaurant_type.1
0      Casual Dining     Casual Dining
1           Delivery          Delivery
2      Casual Dining     Casual Dining
3           Delivery          Delivery
4      Casual Dining     Casual Dining
...              ...               ...
2115   Quick Service     Quick Service
2116   Quick Service     Quick Service
2117   Casual Dining     Casual Dining
2118   Casual Dining     Casual Dining
2119   Casual Dining     Casual Dining

[2120 rows x 2 columns]

In [59]:
df.drop(columns=['restaurant_type.1'],inplace=True)

In [129]:
df.drop(columns=['customer_name'],inplace=True)

In [131]:
df.shape

(1548, 41)

In [62]:
df.isnull().sum()

restaurant_type                    0
restaurant_category                0
cuisine_type                       0
restaurant_name                    0
restaurant_description             0
top_selling_cuisine                0
time_of_order                      0
order_delivered_date               0
time_of_delivery                   0
expected_delivery_time             0
delivery_time_(in_mins)            0
restaurant_id                      0
desc_id                            0
restaurant_location                0
average_rating                     0
category_id                        0
cuisine_id                         0
working_hrs                        0
delivery_available                 0
table_booking_available            0
price                              0
discounts_offered_(%)              0
discounted_price                   0
expected_revenue                   0
customer_name                      0
average_rating.1                   0
order_status                       0
cancellation_reason                0
subscription                       0
actual_revenue                     0
operating_cost                     0
gp_margin                          0
total_number_of_reviews            0
number_of_complaints_received      0
foot_traffic_in_location           0
competitors_in_the_area_(count)    0
budgetd_rev                        0
budgetd_operating_cost             0
budgeted_order                     0
budgeted_gp                        0
acquisition_cost                   0
value                              0
dtype: int64

In [63]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2120 entries, 0 to 2119
Data columns (total 42 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   restaurant_type                  2120 non-null   object
 1   restaurant_category              2120 non-null   object
 2   cuisine_type                     2120 non-null   object
 3   restaurant_name                  2120 non-null   object
 4   restaurant_description           2120 non-null   object
 5   top_selling_cuisine              2120 non-null   object
 6   time_of_order                    2120 non-null   float64
 7   order_delivered_date             2120 non-null   object
 8   time_of_delivery                 2120 non-null   float64
 9   expected_delivery_time           2120 non-null   int64
 10  delivery_time_(in_mins)          2120 non-null   int64
 11  restaurant_id                    2120 non-null   int64
 12  desc_id                          2120 non-null   int64
 13  restaurant_location              2120 non-null   object
 14  average_rating                   2120 non-null   float64
 15  category_id                      2120 non-null   int64
 16  cuisine_id                       2120 non-null   int64
 17  working_hrs                      2120 non-null   object
 18  delivery_available               2120 non-null   object
 19  table_booking_available          2120 non-null   object
 20  price                            2120 non-null   int64
 21  discounts_offered_(%)            2120 non-null   float64
 22  discounted_price                 2120 non-null   float64
 23  expected_revenue                 2120 non-null   float64
 24  customer_name                    2120 non-null   object
 25  average_rating.1                 2120 non-null   float64
 26  order_status                     2120 non-null   object
 27  cancellation_reason              2120 non-null   object
 28  subscription                     2120 non-null   object
 29  actual_revenue                   2120 non-null   float64
 30  operating_cost                   2120 non-null   float64
 31  gp_margin                        2120 non-null   float64
 32  total_number_of_reviews          2120 non-null   int64
 33  number_of_complaints_received    2120 non-null   int64
 34  foot_traffic_in_location         2120 non-null   object
 35  competitors_in_the_area_(count)  2120 non-null   int64
 36  budgetd_rev                      2120 non-null   float64
 37  budgetd_operating_cost           2120 non-null   float64
 38  budgeted_order                   2120 non-null   float64
 39  budgeted_gp                      2120 non-null   float64
 40  acquisition_cost                 2120 non-null   float64
 41  value                            2120 non-null   float64
dtypes: float64(16), int64(10), object(16)
memory usage: 695.8+ KB

# **Fixing Data Types**

In [65]:
df['order_delivered_date'].head()

0    2021-03-01
1    2021-03-01
2    2021-03-01
3    2021-03-01
4    2021-03-01
Name: order_delivered_date, dtype: object

In [66]:
df['order_delivered_date'] = pd.to_datetime(df['order_delivered_date'], format='mixed', errors='coerce')

In [67]:
df['order_delivered_date'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 2120 entries, 0 to 2119
Series name: order_delivered_date
Non-Null Count  Dtype
--------------  -----
2120 non-null   datetime64[ns]
dtypes: datetime64[ns](1)
memory usage: 16.7 KB

In [68]:
df.head()

,restaurant_type,restaurant_category,cuisine_type,restaurant_name,restaurant_description,top_selling_cuisine,time_of_order,order_delivered_date,time_of_delivery,expected_delivery_time,delivery_time_(in_mins),restaurant_id,desc_id,restaurant_location,average_rating,category_id,cuisine_id,working_hrs,delivery_available,table_booking_available,price,discounts_offered_(%),discounted_price,expected_revenue,customer_name,average_rating.1,order_status,cancellation_reason,subscription,actual_revenue,operating_cost,gp_margin,total_number_of_reviews,number_of_complaints_received,foot_traffic_in_location,competitors_in_the_area_(count),budgetd_rev,budgetd_operating_cost,budgeted_order,budgeted_gp,acquisition_cost,value
0,Casual Dining,Snack,Continental,SodaBottleOpenerWala,"[*Parsi, North Indian, Street Food, Desserts, ...",Pizza,0.618750,2021-03-01,0.580556,40,38,43,970,BKC,4.7,2,11,11:00AM - 11:00PM,YES,YES,478,17.42,394.5000,394.5000,Amol Chitale,4.7,Cancelled,Deilvery Partner Behaviour,Gold Subscription,394.5000,279.620000,114.880000,441,5,medium,18,417.560000,264.320000,252.0,133.620000,13.280000,509.3800
1,Delivery,Snack,Vegetarian Snacks,SodaBottleOpenerWala,"[*Parsi, North Indian, Street Food, Desserts, ...",Bhel Puri,0.604016,2021-03-01,0.629711,48,37,13,13,BKC,4.2,2,3,9:00AM - 1:00AM,Yes,No,423,19.96,338.5692,338.5692,Shyam Ghosh,4.0,Fulfilled,Not Cancelled,Gold Subscription,338.5692,267.469668,71.099532,319,33,High,10,385.968888,299.566028,0.0,86.402860,13.392857,84.4308
2,Casual Dining,Snack,Continental,Pizza By The Bay,"[*Italian, Fast Food, Beverages~]\",Pizza,0.441667,2021-03-01,0.204861,45,41,52,977,Churchgate,4.3,2,11,12:00PM - 2:00AM,YES,No,959,26.74,702.6900,702.6900,Chinmay Pawar,4.3,Fulfilled,Not Cancelled,No Subscription,702.6900,448.010000,254.680000,371,1,low,6,825.280000,477.040000,229.0,289.540000,11.860000,957.3700
3,Delivery,Snack,Vegetarian Snacks,SodaBottleOpenerWala,"[*Parsi, North Indian, Street Food, Desserts, ...",Bhel Puri,0.604016,2021-03-01,0.629711,48,37,13,13,BKC,4.2,2,3,9:00AM - 1:00AM,Yes,No,423,19.96,338.5692,338.5692,Shyam Ghosh,4.0,Fulfilled,Not Cancelled,Gold Subscription,338.5692,240.384132,98.185068,319,33,High,10,389.354580,266.826387,0.0,122.528194,17.117117,84.4308
4,Casual Dining,Snack,Continental,Global Fusion,"[*Chinese, Desserts, Beverages~]\",Pizza,0.473611,2021-03-01,0.509722,45,26,77,925,Bandra West,4.4,9,17,11:00AM - 11:00PM,No,YES,537,21.67,420.6300,420.6300,Vikas Modak,4.4,Fulfilled,Not Cancelled,No Subscription,420.6300,267.070000,153.560000,285,4,high,10,472.580000,279.270000,281.0,155.940000,17.570000,574.1900

In [69]:
df[['time_of_order','time_of_delivery']].head()

   time_of_order  time_of_delivery
0       0.618750          0.580556
1       0.604016          0.629711
2       0.441667          0.204861
3       0.604016          0.629711
4       0.473611          0.509722

In [78]:
for col in ['time_of_order', 'time_of_delivery']:
    df[col] = (
        pd.to_timedelta(df[col], unit='D')
        .dt.round('1s')
        .astype(str)
        .str.split().str[-1]
    )

In [79]:
df[['time_of_order','time_of_delivery']].head()

  time_of_order time_of_delivery
0      14:51:00         13:56:00
1      14:29:47         15:06:47
2      10:36:00         04:55:00
3      14:29:47         15:06:47
4      11:22:00         12:14:00

In [84]:
df[df['time_of_order'] > df['time_of_delivery']].shape[0]

214

In [85]:
df = df[(df['time_of_order']) <= (df['time_of_delivery'])]

In [86]:
df.shape

(1906, 42)

In [96]:
df = df[
    (df['time_of_delivery'] - df['time_of_order']) <= pd.Timedelta(hours=2)
]

In [121]:
df.shape

(1548, 42)

In [132]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1548 entries, 1 to 2116
Data columns (total 41 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   restaurant_type                  1548 non-null   object
 1   restaurant_category              1548 non-null   object
 2   cuisine_type                     1548 non-null   object
 3   restaurant_name                  1548 non-null   object
 4   restaurant_description           1548 non-null   object
 5   top_selling_cuisine              1548 non-null   object
 6   time_of_order                    1548 non-null   object
 7   order_delivered_date             1548 non-null   datetime64[ns]
 8   time_of_delivery                 1548 non-null   object
 9   expected_delivery_time           1548 non-null   int64
 10  delivery_time_(in_mins)          1548 non-null   int64
 11  restaurant_id                    1548 non-null   int64
 12  desc_id                          1548 non-null   int64
 13  restaurant_location              1548 non-null   object
 14  average_rating                   1548 non-null   float64
 15  category_id                      1548 non-null   int64
 16  cuisine_id                       1548 non-null   int64
 17  working_hrs                      1548 non-null   object
 18  delivery_available               1548 non-null   object
 19  table_booking_available          1548 non-null   object
 20  price                            1548 non-null   int64
 21  discounts_offered_(%)            1548 non-null   float64
 22  discounted_price                 1548 non-null   float64
 23  expected_revenue                 1548 non-null   float64
 24  average_rating.1                 1548 non-null   float64
 25  order_status                     1548 non-null   object
 26  cancellation_reason              1548 non-null   object
 27  subscription                     1548 non-null   object
 28  actual_revenue                   1548 non-null   float64
 29  operating_cost                   1548 non-null   float64
 30  gp_margin                        1548 non-null   float64
 31  total_number_of_reviews          1548 non-null   int64
 32  number_of_complaints_received    1548 non-null   int64
 33  foot_traffic_in_location         1548 non-null   object
 34  competitors_in_the_area_(count)  1548 non-null   int64
 35  budgetd_rev                      1548 non-null   float64
 36  budgetd_operating_cost           1548 non-null   float64
 37  budgeted_order                   1548 non-null   float64
 38  budgeted_gp                      1548 non-null   float64
 39  acquisition_cost                 1548 non-null   float64
 40  value                            1548 non-null   float64
dtypes: datetime64[ns](1), float64(14), int64(10), object(16)
memory usage: 507.9+ KB

In [99]:
df.sample(5)

,restaurant_type,restaurant_category,cuisine_type,restaurant_name,restaurant_description,top_selling_cuisine,time_of_order,order_delivered_date,time_of_delivery,expected_delivery_time,delivery_time_(in_mins),restaurant_id,desc_id,restaurant_location,average_rating,category_id,cuisine_id,working_hrs,delivery_available,table_booking_available,price,discounts_offered_(%),discounted_price,expected_revenue,customer_name,average_rating.1,order_status,cancellation_reason,subscription,actual_revenue,operating_cost,gp_margin,total_number_of_reviews,number_of_complaints_received,foot_traffic_in_location,competitors_in_the_area_(count),budgetd_rev,budgetd_operating_cost,budgeted_order,budgeted_gp,acquisition_cost,value
1203,Delivery,Breakfast,Contemporary Indian,Jamjar Diner,"[*Continental, Sandwich, Burger, Italian, Mexi...",Egg Omlette,0 days 18:47:26,2021-02-20,0 days 19:37:26,46,50,15,15,Versova,4.2,5,9,9:00AM - 1:00AM,Yes,Yes,606,13.35,525.0990,525.0990,Naveen Das,4.0,Fulfilled,Not Cancelled,Gold Subscription,525.0990,378.071280,147.027720,144,10,Low,9,593.361870,427.220546,0.0,166.141324,14.159292,80.9010
1403,Casual Dining,Main Course,Veg Thali,Shree Thaker Bhojanalay,[*Gujarati~]\,Thali,0 days 22:49:54,2021-02-26,0 days 23:26:54,63,37,4,4,Kalbadevi,4.7,1,11,"11:30AM - 3:30PM, 7:00PM - 10:30PM",No,No,1038,22.36,805.9032,805.9032,Mahesh Saxena,4.6,Cancelled,Deilvery Partner Behaviour,No Subscription,0.0000,402.951600,-402.951600,383,29,Medium,43,0.000000,463.394340,0.0,-463.394340,14.782609,232.0968
276,Delivery,Main Course,Maharashtrian,The Bombay Canteen,"[*Modern Indian, Bar Food, Beverages~]\",Pav Bhaji,0 days 02:48:03,2021-03-09,0 days 03:31:03,42,43,1,1,Lower Parel,4.7,1,2,12:00PM - 1:30AM,Yes,No,971,19.53,781.3637,781.3637,Tejas Sarin,4.7,Cancelled,Delayed,No Subscription,0.0000,390.681850,-390.681850,302,14,High,50,0.000000,441.470490,0.0,-441.470490,17.699115,189.6363
1276,Delivery,Appetizer,North Indian,Jamjar Diner,"[*Continental, Sandwich, Burger, Italian, Mexi...",Chicken Lollipop,0 days 00:36:55,2021-02-22,0 days 01:29:55,42,53,15,15,Versova,4.2,6,4,9:00AM - 1:00AM,Yes,Yes,572,18.96,463.5488,463.5488,Ashok Shetty,4.0,Fulfilled,Not Cancelled,Gold Subscription,463.5488,338.390624,125.158176,290,92,Low,34,533.081120,375.613593,0.0,157.467527,14.414414,108.4512
892,Delivery,Breakfast,South Indian,Ram Ashraya,"[*South Indian, Beverages~]\",Dosa,0 days 05:35:25,2021-02-07,0 days 06:27:25,58,52,7,7,Matunga East,4.7,5,10,5:00AM - 10:00PM,Yes,No,141,8.22,129.4098,129.4098,Deepak Bhat,4.3,Fulfilled,Not Cancelled,Gold Subscription,129.4098,91.880958,37.528842,235,49,Medium,42,147.527172,101.069054,0.0,46.458118,13.636364,11.5902

In [102]:
for col in ['time_of_order', 'time_of_delivery']:
    df[col] = (
        df[col]
        .astype(str)
        .str.split()
        .str[-1]
    )

In [103]:
df.sample(5)

,restaurant_type,restaurant_category,cuisine_type,restaurant_name,restaurant_description,top_selling_cuisine,time_of_order,order_delivered_date,time_of_delivery,expected_delivery_time,delivery_time_(in_mins),restaurant_id,desc_id,restaurant_location,average_rating,category_id,cuisine_id,working_hrs,delivery_available,table_booking_available,price,discounts_offered_(%),discounted_price,expected_revenue,customer_name,average_rating.1,order_status,cancellation_reason,subscription,actual_revenue,operating_cost,gp_margin,total_number_of_reviews,number_of_complaints_received,foot_traffic_in_location,competitors_in_the_area_(count),budgetd_rev,budgetd_operating_cost,budgeted_order,budgeted_gp,acquisition_cost,value
65,Delivery,Breakfast,Contemporary Indian,Aaswad,"[*Maharashtrian, South Indian, Street Food, Fa...",Egg Omlette,12:51:29,2021-03-02,13:42:29,35,51,6,6,Dadar West,4.4,5,9,9:30AM - 10:00PM,No,No,531,5.42,502.2198,502.2198,Manoj Dubey,4.4,Fulfilled,Not Cancelled,Gold Subscription,502.2198,361.598256,140.621544,450,66,High,43,567.508374,404.990047,0.0,162.518327,16.071429,28.7802
24,Delivery,Snack,Vegetarian Snacks,SodaBottleOpenerWala,"[*Parsi, North Indian, Street Food, Desserts, ...",Bhel Puri,14:29:47,2021-03-01,15:06:47,48,37,13,13,BKC,4.2,2,3,9:00AM - 1:00AM,Yes,No,423,19.96,338.5692,338.5692,Shyam Ghosh,4.0,Fulfilled,Not Cancelled,Gold Subscription,338.5692,250.541208,88.027992,319,33,High,10,385.968888,285.616977,0.0,100.351911,14.912281,84.4308
1200,Delivery,Breakfast,Contemporary Indian,Jamjar Diner,"[*Continental, Sandwich, Burger, Italian, Mexi...",Egg Omlette,18:47:26,2021-02-20,19:37:26,46,50,15,15,Versova,4.2,5,9,9:00AM - 1:00AM,Yes,Yes,606,13.35,525.0990,525.0990,Naveen Das,4.0,Fulfilled,Not Cancelled,Gold Subscription,525.0990,420.079200,105.019800,144,10,Low,9,577.608900,483.091080,0.0,94.517820,13.913043,80.9010
1559,Delivery,Main Course,North Indian,Gajalee,"[*Seafood, Maharashtrian, Mughlai, North India...",Chicken Biryani,01:03:49,2021-01-09,01:44:49,56,41,9,9,Vile Parle East,4.2,1,4,"11:30AM - 3:30PM, 6:30PM - 11:30PM",Yes,Yes,268,8.74,244.5768,244.5768,Aditya Yadav,4.3,Fulfilled,Not Cancelled,Gold Subscription,244.5768,171.203760,73.373040,474,14,Low,19,273.926016,191.748211,0.0,82.177805,17.857143,23.4232
402,Delivery,Dessert,Bakery & Cafe,The Bombay Canteen,"[*Modern Indian, Bar Food, Beverages~]\",Gulab Jamun,15:46:52,2021-03-15,16:26:52,59,40,1,1,Lower Parel,4.7,4,5,12:00PM - 1:30AM,Yes,No,650,2.22,635.5700,635.5700,Ashok Dwivedi,4.2,Cancelled,No Longer Needed,No Subscription,0.0000,317.785000,-317.785000,339,78,High,7,0.000000,365.452750,0.0,-365.452750,13.043478,14.4300

In [108]:
print(df['restaurant_description'].head())

1    [*Parsi, North Indian, Street Food, Desserts, ...
3    [*Parsi, North Indian, Street Food, Desserts, ...
4                    [*Chinese, Desserts, Beverages~]\
5    [*Parsi, North Indian, Street Food, Desserts, ...
6    [*Parsi, North Indian, Street Food, Desserts, ...
Name: restaurant_description, dtype: object

In [110]:
count = 0
for i in df['restaurant_description']:
    print(i)
    count+=1
    if count==5:
        break

[*Parsi, North Indian, Street Food, Desserts, Beverages~]\
[*Parsi, North Indian, Street Food, Desserts, Beverages~]\
[*Chinese, Desserts, Beverages~]\
[*Parsi, North Indian, Street Food, Desserts, Beverages~]\
[*Parsi, North Indian, Street Food, Desserts, Beverages~]\

In [111]:
df['restaurant_description'] = (
    df['restaurant_description']
    .str.replace(r'[\[\]\*~\\]', '', regex=True)
)

In [114]:
count = 0
for i in df['restaurant_description']:
    print(i)
    count+=1
    if count==5:
        break

Parsi, North Indian, Street Food, Desserts, Beverages
Parsi, North Indian, Street Food, Desserts, Beverages
Chinese, Desserts, Beverages
Parsi, North Indian, Street Food, Desserts, Beverages
Parsi, North Indian, Street Food, Desserts, Beverages

In [117]:
file_path = "clean_data.csv"
df.to_csv(file_path, index=False)

In [122]:
df.columns

Index(['restaurant_type', 'restaurant_category', 'cuisine_type',
       'restaurant_name', 'restaurant_description', 'top_selling_cuisine',
       'time_of_order', 'order_delivered_date', 'time_of_delivery',
       'expected_delivery_time', 'delivery_time_(in_mins)', 'restaurant_id',
       'desc_id', 'restaurant_location', 'average_rating', 'category_id',
       'cuisine_id', 'working_hrs', 'delivery_available',
       'table_booking_available', 'price', 'discounts_offered_(%)',
       'discounted_price', 'expected_revenue', 'customer_name',
       'average_rating.1', 'order_status', 'cancellation_reason',
       'subscription', 'actual_revenue', 'operating_cost', 'gp_margin',
       'total_number_of_reviews', 'number_of_complaints_received',
       'foot_traffic_in_location', 'competitors_in_the_area_(count)',
       'budgetd_rev', 'budgetd_operating_cost', 'budgeted_order',
       'budgeted_gp', 'acquisition_cost', 'value'],
      dtype='object')

In [123]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1548 entries, 1 to 2116
Data columns (total 42 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   restaurant_type                  1548 non-null   object
 1   restaurant_category              1548 non-null   object
 2   cuisine_type                     1548 non-null   object
 3   restaurant_name                  1548 non-null   object
 4   restaurant_description           1548 non-null   object
 5   top_selling_cuisine              1548 non-null   object
 6   time_of_order                    1548 non-null   object
 7   order_delivered_date             1548 non-null   datetime64[ns]
 8   time_of_delivery                 1548 non-null   object
 9   expected_delivery_time           1548 non-null   int64
 10  delivery_time_(in_mins)          1548 non-null   int64
 11  restaurant_id                    1548 non-null   int64
 12  desc_id                          1548 non-null   int64
 13  restaurant_location              1548 non-null   object
 14  average_rating                   1548 non-null   float64
 15  category_id                      1548 non-null   int64
 16  cuisine_id                       1548 non-null   int64
 17  working_hrs                      1548 non-null   object
 18  delivery_available               1548 non-null   object
 19  table_booking_available          1548 non-null   object
 20  price                            1548 non-null   int64
 21  discounts_offered_(%)            1548 non-null   float64
 22  discounted_price                 1548 non-null   float64
 23  expected_revenue                 1548 non-null   float64
 24  customer_name                    1548 non-null   object
 25  average_rating.1                 1548 non-null   float64
 26  order_status                     1548 non-null   object
 27  cancellation_reason              1548 non-null   object
 28  subscription                     1548 non-null   object
 29  actual_revenue                   1548 non-null   float64
 30  operating_cost                   1548 non-null   float64
 31  gp_margin                        1548 non-null   float64
 32  total_number_of_reviews          1548 non-null   int64
 33  number_of_complaints_received    1548 non-null   int64
 34  foot_traffic_in_location         1548 non-null   object
 35  competitors_in_the_area_(count)  1548 non-null   int64
 36  budgetd_rev                      1548 non-null   float64
 37  budgetd_operating_cost           1548 non-null   float64
 38  budgeted_order                   1548 non-null   float64
 39  budgeted_gp                      1548 non-null   float64
 40  acquisition_cost                 1548 non-null   float64
 41  value                            1548 non-null   float64
dtypes: datetime64[ns](1), float64(14), int64(10), object(17)
memory usage: 520.0+ KB